const Map<String, dynamic> countries = {
  'Country': 'kco',
  "Russia": 'ru',
  "Ukrain": "ua",
  "Kazakhstan": 'kz',
  'Great britain': 'gb',
  'France': 'fr',
  'Germany': 'de',
  'Italy': 'it',
  'Spain': 'es',
  'Turkey': 'tr',
  'Belarus': 'by',
  'Austria': 'at',
  'Belgium': 'be',
  'Bulgaria': 'bg',
  'Croatia': 'hr',
  'Cyprus': 'cy',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  "Estonia": 'ee',
  'Finland': 'fi',
  'Greece': 'gr',
  'Hungary': 'hu',
  'Ireland': 'ie',
  'Lativia': 'lv',
  'Luxembourg': 'lu',
  'Netherlands': 'nl',
  'Poland': 'pl',
  'Romania': 'ro',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Sweden': 'se',
  "Israel": 'il'
};
